### ISSUE TITLE
LSTM restoration

### ISSUE THREAD

**Issue by notimesea** [soumith/cudnn.torch#256]
Is there any reference how to restore weights of LSTM to serialize model? (e.g. to rnn SeqLSTM).

In other words how to understand which part of self.weight part corresponds to each LSTM weights part (W_i, R_i, bW_i, bR_i, W_f, R_f, bW_f, bR_f, W_o, R_o, bW_o, bR_o, W_c, R_c, bW_c, bR_c)
It is needed to run pre-learned model on CPU.

P.S. There is no cudnn.convert for this layer :(

**Comment by ngimel** [comment]
RNN:weights() and RNN:biases() return tables of tensors corresponding to each weight/bias part. Please look in the RNN.lua source and refer to cudnn manual for cudnnGetRNNLinLayerMatrixParams and cudnnGetRNNLinLayerBiasParams for information on what table member corresponds to what matrix. There is no cudnn.convert for this layer because RNN and LSTM are not part of nn package.

**Comment by JoostvDoorn** [comment]
For now you can use this to convert between SeqLSTM and cudnn.LSTM: https://gist.github.com/JoostvDoorn/bd43ce85a101c0aeee03f734ead688fb

It will be helpful if this can be done in the same manner as cudnn.convert.
