### ISSUE TITLE
Larger batch sizes for RNNs

### ISSUE THREAD

**Issue by SeanNaren** [soumith/cudnn.torch#259]
Hey, I've been trying to scale up the batch sizes for the RNNs but they require a lot of memory in the forward/backward reserves to run training. Is there a way to re-use these reserves across RNNs to help reduce the overheads of memory?

**Comment by ngimel** [comment]
Not a lot you can do here. You can try using optnet, but for it to work correctly you have to call :backward() rather than :updateGradInput() and :accGradParameters() (otherwise you can not reuse gradInputs of the different layers). reserveSpace has to be preserved between forward and backward, so you cannot reuse it across rnns. Shorter sequences can be calculated with bigger batches (provides nice perf benefit too), but batch size for longer sequences will be limited.

**Comment by SeanNaren** [comment]
Thanks for that, and I like the idea of smaller batches for longer sequence lengths seems the best choice if reserve space has to be maintained. Thanks @ngimel  :)

**Comment by ekelsen** [comment]
Note that as far as the benchmark is concerned, I don't think that bigger batches for shorter sequences should be allowed.  It can have serious effects on the optimization effects and if you don't do it right can significantly hurt performance.  And then we would have to specify how big a batch can be allowed to get and all sorts of other hyper-parameters.
