### ISSUE TITLE
Contiguous tensors behavior?

### ISSUE THREAD

**Issue by suryabhupa** [soumith/cudnn.torch#305]
In lines such as these: https://github.com/soumith/cudnn.torch/blob/master/RNN.lua#L303-L316, is there a reason why the tensors are not automatically made to be contiguous if they are not? Is there a notable performance hit if these were to be the case?

**Comment by ngimel** [comment]
It typically involves allocating new tensor, copying an old one to it and garbage-collecting an old tensor. 
https://github.com/soumith/cudnn.torch/blob/master/RNN.lua#L207-L219
It is less of a performance issue with caching allocator, and on single GPU runs, and it is worse without caching allocator. Since you are typically in charge of how you are creating hidden tensors, better to make them contiguous from the beginning.

**Comment by suryabhupa** [comment]
I see. I'll do my best to make sure that this invariant is maintained in my code. Thanks!
