### ISSUE TITLE
clearState() of SpatialFullConvolution is missing input_slice / output_slice

### ISSUE THREAD

**Issue by sniklaus** [soumith/cudnn.torch#313]
The `clearState()` of SpatialConvolution contains the following line:

```nn.utils.clear(self, '_input', '_gradOutput', 'input_slice', 'output_slice')```

This line is missing in the `clearState()` of SpatialFullConvolution. While `_input` and `_gradOutput` are used to make the respective tensors contiguous and I do not see them being used in SpatialFullConvolution, the `input_slice` and the `output_slice` seem to be used and are thus not being cleared.

It might be useful to move some of this functionality into the `clearDesc()` of SpatialConvolution, which is also called by SpatialFullConvolution.

**Comment by ngimel** [comment]
Input_slice and output_slice share storage with input and output respectively, so there is no need to clear them separately.

**Comment by sniklaus** [comment]
Are you sure? The following ends up saving over 200 megabytes.

```
require 'cudnn'

input = torch.rand(1000, 10, 32, 32):cuda()
gradInput = torch.rand(1000, 10, 16, 16):cuda()

net = cudnn.SpatialFullConvolution(10, 10, 4, 4, 2, 2, 1, 1):cuda()

net:forward(input)
net:backward(input, gradInput)

torch.save('net.t7', net:clearState())
```

**Comment by ngimel** [comment]
Ah, you are right. Perhaps SpatialFullConvolution's clearState should just call SpatialConvolution's clearState.

**Comment by shamangary** [comment]
SpatialConvolution has the similar issue, but it is actually an issue of **cudnn.convert()**. 
(Or you can say the problem is about the clearState() under nn.)

If you have a trained model which is cudnn based and you convert it to nn by cudnn.convert(model,nn), **input_slice** and **output_slice** will not be clear by clearState() under nn.

You have to convert it back to cudnn and then do clearState() and then convert it back to nn.
I hope this can be fixed......
